### ISSUE TITLE
Implement Proper Logging System

### ISSUE THREAD

**Issue by zaynabtariq** [AgLyx3/Group-Sprint-1-Bookazon#2] opened 2024-09-27 02:55 UTC
Replace System.out.println() calls with a proper logging framework to improve debugging and monitoring capabilities.

**Comment by cathymonkey** [comment] 2024-09-30 22:33
There are no major defects, and the issue is not significant to the project. Therefore, we will proceed with closing it.

**Closed as completed** 2024-09-30 22:33 UTC
Labels: enhancement, wontfix
